config/routes.rb
Rails.application.routes.draw do

  get "/", to: "home#index"

  get "/sign-up", to: "home#sign_up"
  post "/sign-up", to: "home#create_user"
  get "/log-in", to: "home#login"
  post "/log-in", to: "home#login"
  get "/log-out", to: "home#logout", as: :logout
  get "/myaccount", to: "home#account", as: :account
  post "/myaccount", to: "home#update_email", as: :update_email

  get "/addpic", to: "addpic#index", as: :addpic
  post "/addpic", to: "addpic#addpic"

  get "/mymoments", to: "moment#index", as: :moment_home
  get "/mymoments/:id", to: "moment#show", as: :show_one
  delete "mymoments/:id", to: "moment#delete", as: :delete

  get "/review-images", to: "review#review_images", as: :review_images
  post "/review-images", to: "review#rate_image", as: :rate_image

  get "/user-photos", to: "review#user_photos", as: :user_photos
  get "/user-photo/:id", to: "review#show", as: :user_show_one

  get "/rankings", to: "review#rankings", as: :rankings

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :url, ImageFileUploader

  validates :name, presence: true
  validates :url, presence: true

  has_many :reviews
  validates_associated :reviews
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :rating, presence: true

  belongs_to :picture
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :user, presence: true
  validates :email, format: /@/

  has_many :pictures
  has_many :reviews
  validates_associated :reviews
  validates_associated :pictures
end

app/controllers/addpic_controller.rb
class AddpicController < ApplicationController

  def index

  end

  def addpic
    @picture = Picture.new
    @picture.name = params[:name]
    @picture.description = params[:description]
    @picture.user_id = current_user.id
    @picture.url = params[:url]
    # @picture.username = User.find(current_user.id).user
    if @picture.save
      redirect_to "/mymoments", notice: "#{@picture.name} has been added to your captured moments!"
    else
      @picture.destroy
      flash.now[:notice] = "Error adding photo, make sure to fill in all required fields."
      render "addpic/index"
    end
  end


  private

    def addpic_params
      params.require(:picture).permit(:name, :description, :url)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  def create_user
    @users = User.all
    @users.each do |user|
      if user.user == params[:username] || user.email == params[:email]
        redirect_to "/log-in", notice: "You have already signed up. Please log in."
        return
      end
    end
    @user = params[:username]
    @email = params[:email]
    if params[:password] != params[:password_confirmation]
      flash.now[:notice] = "Passwords do not match."
      render "home/sign_up"
    else
      @user = User.new
      @user.user = params[:username]
      @user.email = params[:email]
      @user.password = params[:password]
      if @user.save
        session[:user_id] = @user.id
        redirect_to "/mymoments", notice: "You have successfully signed up!"
      else
        render "sign_up"
      end
    end
  end

  def login
    @user = User.find_by(user: params[:user])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/mymoments", flash: {success: "You have successfully logged in."}
    else
      # flash.now[:notice] = "Wrong username/password."
      render "login"
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to "/", notice: "You have successfully logged out."
  end

  def account
    @user = current_user
  end

  def update_email
    @user = current_user
    @user.email = params[:email]
    if @user.save
      redirect_to "/myaccount", notice: "You have successfully changed your email!"
    else
      redirect_to "/myaccount", notice: "Please enter a valid email address."
    end
  end

end

app/controllers/moment_controller.rb
class MomentController < ApplicationController

  def index
    @pictures = Picture.all.where(user_id: current_user.id)
  end

  def show
    @picture = Picture.find(params[:id])
    @reviews = Review.where(picture_id: @picture.id)
    @thumbs_ups = @reviews.where(rating: 1).count
    @okays = @reviews.where(rating: 0).count
    @thumbs_downs = @reviews.where(rating: -1).count

    @has_comments = false
    @reviews.each do |review|
      if review.comment != ""
        @has_comments = true
        break
      end
    end
  end

  def delete
    @picture = Picture.find(params[:id])
    picture_name = @picture.name
    @picture.destroy
    redirect_to "/mymoments", notice: "#{picture_name} has been deleted!"
  end

end

app/controllers/review_controller.rb
class ReviewController < ApplicationController

  def review_images
    # First get a list of all pictures the current user has reviewed
    reviewed_pictures = Picture.joins(:reviews).where(["reviews.user_id = ?", current_user.id])

    # Next get a list of all pictures NOT associated with the user
    other_user_pictures = Picture.all.where.not(user_id: current_user.id)

    # Remove all pictures reviewed by the current user from the list of pictures NOT associated with the user to get a list of unreviewed pictures
    unreviewed_pictures = other_user_pictures - reviewed_pictures

    # Choose a random unreviewed picture to review
    @picture = unreviewed_pictures.shuffle.first
  end

  def user_photos
    @user = User.find(params[:user_id])
    @pictures = Picture.all.where(user_id: params[:user_id])
  end

  def show
    @picture = Picture.find(params[:id])
    @reviews = Review.where(picture_id: @picture.id)
    @thumbs_ups = @reviews.where(rating: 1).count
    @okays = @reviews.where(rating: 0).count
    @thumbs_downs = @reviews.where(rating: -1).count

    @has_comments = false
    @reviews.each do |review|
      if review.comment != ""
        @has_comments = true
        break
      end
    end
  end

  def rate_image
    @review = Review.new
    @review.comment = params[:comment]
    @review.rating = params[:rating]
    @review.picture_id = params[:id]
    @review.user_id = current_user.id
    if @review.save
      RatingMailer.rating_email((Picture.find(@review.picture_id)).user_id, @review.id).deliver_now
      redirect_to "/review-images"
    else
      @picture = Picture.find(params[:id])
      render "review/review_images"
    end
  end

  def show_rating
    @reviews = Review.all.where(picture_id: @picture.id)
  end

  def rankings
    @pics = Picture.all
    @pics = @pics.sort { |pic1, pic2| get_picture_net_rating(pic2) <=> get_picture_net_rating(pic1) }
  end

  def get_picture_net_rating(picture)
    reviews = Review.where(picture_id: picture.id)
    net = 0
    reviews.each do |review|
      net += review.rating
    end
    net
  end

end

app/controllers/session_controller.rb
# class SessionController < ApplicationController
#
#   def login
#     @user = User.find_by(user: params[:user])
#     if @user && @user.authenticate(params[:password])
#       session[:user_id] = @user.id
#       redirect_to "/mymoments", flash: {success: "You have successfully logged in."}
#     else
#       render "home/login", flash: {warning: "Wrong username/password."}
#     end
#   end
#
#   def logout
#     session.delete(:user_id)
#     redirect_to "/", notice: "You have successfully logged out."
#   end
#
# end

app/controllers/user_controller.rb
# class UserController < ApplicationController
#
#   def index
#
#   end
#
#   def new
#
#   end
#
#   def create
#     @user = User.create(params)
#   end
#
# end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(email)
      hashed_email = Digest::MD5.hexdigest(email.downcase.strip)
      image_tag "http://www.gravatar.com/avatar/#{hashed_email}.jpg"
    end

end

app/views/addpic/index.html.erb
<h1>Add a Photo!</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class = "form">

        <form action="/addpic" method="POST" enctype="multipart/form-data">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
          <div>
            <h4>
              <label for="name-input">IMAGE NAME</label>
            </h4>
            <input class="name-input" type="text" id = "name-input" name="name" />
          </div>
          <div>
            <h4>
              <label for="description-input">IMAGE DESCRIPTION (optional)</label>
            </h4>
            <input class="description-input" type="text" id = "description-input" name="description" value="None"/>
          </div>
          <div>
            <h4>
              <label for="image-input">IMAGE URL</label>
            </h4>
            <input class="file" type="file" id = "image-input" name="url" />
          </div>
          <div class="submit">
            <input type="submit" class="btn btn-default" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/home/account.html.erb
<h1>My Account</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12 account">
      <%= gravatar_for @user.email %>

      <form action="/myaccount" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
        <div>
          <h4>
            <label for="name-input">Update Email Address</label>
          </h4>
          <input class="email-input" type="text" id = "email-input" name="email" value="<%= current_user.email %>" />
        </div>
        <div class="update">
          <input type="submit" value="Update" class="btn btn-default" />
        </div>
      </form>


    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="home_header">
        <h1>Sharp Shooter</h1>
        <p>Welcome to Sharp Shooter, where you can upload your photos and have it reviewed by your peers.</p>
        <button><%= link_to "Sign Up!", "/sign-up" %></button>
      </div>
      <img src="https://s3-us-west-2.amazonaws.com/photo-rating/photobg.png" alt="" class="img-responsive center-block"/>
    </div>
  </div>
</div>

<div class="space">

</div>

app/views/home/login.html.erb
<div class="container">
  <div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
      <div class="panel panel-default">
      	<div class="panel-heading">
		    	<h3 class="panel-title">Log In to Sharp Shooter</h3>
		 		</div>
		 		<div class="panel-body">
			  	<form role="form" action="/log-in" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
            <div class="form-group">
		    			<input type="user" name="user" id="user" class="form-control input-sm" placeholder="Username" />
			  		</div>
            <div class="form-group">
		    			<input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
		  			</div>
		    		<input type="submit" value="Log In" class="btn btn-info btn-block">
			    </form>
			  </div>
    	</div>
  	</div>
  </div>
</div>

app/views/home/sign_up.html.erb
<div class="container">
    <div class="row centered-form">
      <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        <div class="panel panel-default">
        	<div class="panel-heading">
			    	<h3 class="panel-title">Sign Up for Sharp Shooter</h3>
			 		</div>
			 		<div class="panel-body">
			    	<form role="form" action="/sign-up" method="POST">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
              <div class="form-group">
			    			<input type="username" name="username" id="username" class="form-control input-sm" placeholder="Username" value="<%= @user %>">
			  			</div>
              <div class="form-group">
			    			<input type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address" value="<%= @email %>">
			  			</div>
		    			<div class="row">
		    				<div class="col-xs-6 col-sm-6 col-md-6">
		    					<div class="form-group">
		    						<input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
		    					</div>
		    				</div>
		    				<div class="col-xs-6 col-sm-6 col-md-6">
		    					<div class="form-group">
		    						<input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-sm" placeholder="Confirm Password">
		    					</div>
		    				</div>
		    			</div>
			    		<input type="submit" value="Sign Up" class="btn btn-info btn-block">
			    	</form>
			    </div>
	    	</div>
    	</div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sharp Shooter</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <% if flash.key?(:notice) %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash.key?(:warning) %>
    <div class="alert alert-danger">
      <%= flash[:warning] %>
    </div>
  <% end %>

  <% if flash.key?(:success) %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>

  <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Sharp Shooter", "/", class: "navbar-brand" %>
          <button class="navbar-toggle collapsed" data-toggle="collapse" data-target=".menu_bar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="menu_bar collapse navbar-collapse">
          <div class="navbar-right">
            <ul class="nav navbar-nav">
              <% if current_user %>
                <li><%= link_to "Pic Peer Review", review_images_path %></li>
                <li><%= link_to "Add File", addpic_path %></li>
                <li><%= link_to "Moments Captured", moment_home_path %></li>
                <li><%= link_to "My Account", account_path %></li>
                <li><%= link_to "Sign Out", logout_path %></li>
              <% else %>
                <li><%= link_to "Log In", "/log-in" %></li>
                <li><%= link_to "Sign Up", "/sign-up" %></li>
              <% end %>
            </ul>
          </div>


        </div>
      </div>
    </nav>

<%= yield %>

</body>
</html>

app/views/moment/index.html.erb
<h1>My Captured Moments</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% @pictures.in_groups_of(4, false).each do |group| %>
        <div class="row">
          <% group.each do |picture| %>
            <div class="product col-md-3 index">
              <a><%= link_to picture.name, show_one_path(picture.id) %></a>
              <li><%= picture.description %></li>
              <img><%= link_to image_tag(picture.url.url(:square)), show_one_path(picture.id) %></img>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/moment/show.html.erb
<h1><%= @picture.name %></h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="picture-details" id="picture-details">
        <img><%= image_tag @picture.url.url(:big) %></img>
        <div class="photo-info">
          <li>Name: <%= @picture.name %></li>
          <li>Description: <%= @picture.description %></li>
          <% reviews = Review.all.where(picture_id: @picture.id) %>
          <br>
          <p>Reviews</p>
          <div class="thumbs-up">
            <span class="glyphicon glyphicon-thumbs-up"></span> : <%=@thumbs_ups %>
          </div>
          <div class="okay">
            <span class="glyphicon glyphicon-question-sign"></span> : <%=@okays %>
          </div>
          <div class="thumbs-down">
            <span class="glyphicon glyphicon-thumbs-down"></span> : <%=@thumbs_downs %>
          </div>
          <br>
          <div class=comments>
            <p>Comments</p>
            <% if @has_comments %>
              <% @reviews.each do |review| %>
                <% if review.comment != "" %>
                  <%= link_to User.find(review.user_id).user, user_photos_path(user_id: review.user.id) %>: "<%=review.comment %>"<br>
                <% end %>
              <% end %>
            <% else %>
              No comments yet.
            <% end %>
          </div>
          <br>
          <form action="/mymoments/<%= @picture.id %>" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
            <input type="hidden" name="_method" value="DELETE" />
            <input type="submit" value="Delete Picture" class="btn btn-default" data-confirm="Delete the picture?" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/review/rankings.html.erb
<h1>Image Rankings</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% @pics.in_groups_of(4, false).each do |group| %>
        <div class="row">
          <% group.each do |pic| %>
            <div class="product col-md-3 index">
              <a><%= link_to pic.name, user_show_one_path(pic.id) %></a>
              <li><%= pic.description %></li>
              <img><%= link_to image_tag(pic.url.url(:square)), user_show_one_path(pic.id) %></img>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/review/review_images.html.erb
<h1>Review Images!</h1>

<div class=nil>
  <% if @picture == nil %>
    <h2><%= "You have reviewed all images." %></h2>
  <% else %>
</div>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="picture-details" id="picture-details">
          <img><%= image_tag @picture.url.url(:big) %></img>
          <div class="photo-info">
            <li>Name: <%= @picture.name %></li>
            <li>Description: <%= @picture.description %></li>
            <li>Taken by: <%= link_to @picture.user.user, user_photos_path(user_id: @picture.user.id) %></li>
            <li><%= gravatar_for(@picture.user.email) %></li>
            <form action="<%= rate_image_path(id: @picture.id) %>" method="POST" class="rating" enctype="multipart/form-data">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
              <label for="rating" class="control-label input-group"></label>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default">
                  <input name="rating" value="1" type="radio">
                  <span class="glyphicon glyphicon-thumbs-up"></span>
                </label>
                <label class="btn btn-default">
                  <input name="rating" value="0" type="radio">
                  <span class="glyphicon glyphicon-question-sign"></span>
                </label>
                <label class="btn btn-default">
                  <input name="rating" value="-1" type="radio">
                  <span class="glyphicon glyphicon-thumbs-down"></span>
                </label>
              </div>
              <div class="comment-input">
                <textarea type="textarea" id = "comment-input" name="comment" placeholder="Leave a Comment (Optional)"/></textarea>
              </div>
              <button type="submit" class="btn btn-default comment-btn">Submit Review</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="rating-links">
  <li><%= link_to "Image Rankings", rankings_path %></li>
</div>

app/views/review/show.html.erb
<h1><%= @picture.name %></h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="picture-details" id="picture-details">
        <img><%= image_tag @picture.url.url(:big) %></img>
        <div class="photo-info">
          <li>Name: <%= @picture.name %></li>
          <li>Description: <%= @picture.description %></li>
          <li>Taken by: <%= link_to @picture.user.user, user_photos_path(user_id: @picture.user.id) %></li>
          <li><%= gravatar_for(@picture.user.email) %></li>
          <br>
          <p>Reviews</p>
          <div class="thumbs-up">
            <span class="glyphicon glyphicon-thumbs-up"></span> : <%=@thumbs_ups %>
          </div>
          <div class="okay">
            <span class="glyphicon glyphicon-question-sign"></span> : <%=@okays %>
          </div>
          <div class="thumbs-down">
            <span class="glyphicon glyphicon-thumbs-down"></span> : <%=@thumbs_downs %>
          </div>
          <br>
          <div class=comments>
            <p>Comments</p>
            <% if @has_comments %>
              <% @reviews.each do |review| %>
                <% if review.comment != "" %>
                  <%= link_to User.find(review.user_id).user, user_photos_path(user_id: review.user.id) %>: "<%=review.comment %>"<br>
                <% end %>
              <% end %>
            <% else %>
              No comments yet.
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/review/user_photos.html.erb
<div class="upcase-username">
  <h1><%= @user.user %>'s Images</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% @pictures.in_groups_of(4, false).each do |group| %>
        <div class="row">
          <% group.each do |picture| %>
            <div class="product col-md-3 index">
              <a><%= link_to picture.name, user_show_one_path(picture.id) %></a>
              <li><%= picture.description %></li>
              <img><%= link_to image_tag(picture.url.url(:square)), user_show_one_path(picture.id) %></img>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>